name: Build Mac

on: [push]

jobs:
  mac:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install pyinstaller ecdsa jcs requests

      - name: Debug files
        run: ls -la

      - name: Build Mac app
        run: |
          pyinstaller \
            --windowed \
            --name "PrintGUI" \
            --add-data "$(pwd)/fingerprint.png:." \
            printGUI.py

      - name: Create DMG
        run: |
          mkdir dmg
          cp -R "dist/PrintGUI.app" dmg/
          hdiutil create -volname "PrintGUI" -srcfolder dmg -ov -format UDZO PrintGUI-mac.dmg

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: PrintGUI-Mac
          path: PrintGUI-mac.dmg
